Bump Apicurio Registry version to 2.4.2.Final
dmuharemagic/apicurio-registry-gradle-plugin pull request #16
Opened 2023-04-28 12:28 UTC by andreaTP

First of all, thanks for this plugin!

Fix: https://github.com/Apicurio/apicurio-registry/issues/3301

The significant changes are because `ArtifactType` is now mapped to a simple `String` to allow for user-defined extensions (e.g. we got requests for BigQuery).

2023-05-02 12:44 UTC, dmuharemagic commented
Thank you for the contribution to the project. Means a lot!
Left a comment to look out for. I'll be happy to integrate the additional changes if necessary.

2023-05-02 12:44 UTC, dmuharemagic requested changes

2023-05-02 12:44 UTC, dmuharemagic commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
I agree with notion of making the artifact type more flexible, however we still need to deal with the file extensions properly.
When executing the download task , this would produce an output file name of e.g. Person.AVRO, which does not have the proper extension that corresponds to that format.
Perhaps we could be explicit about the extension by integrating it into the `outputPath` property of [DownloadArtifact](https://github.com/croz-ltd/apicurio-registry-gradle-plugin/blob/main/plugin/src/main/kotlin/net/croz/apicurio/model/DownloadArtifact.kt), and omit the `outputFileName` property?

2023-05-02 12:48 UTC, dmuharemagic requested changes
Additionally, we need to bump the plugin version located [here](https://github.com/croz-ltd/apicurio-registry-gradle-plugin/blob/main/plugin/gradle.properties) to support a proper release. (https://github.com/croz-ltd/apicurio-registry-gradle-plugin/blob/main/plugin/gradle.properties).

2023-05-02 12:49 UTC, andreaTP commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
What you are proposing seems reasonable to me.
Since I'm not familiar with the project, would you mind taking over this work?
Feel free to close this PR and come up with an alternative one, PR to my fork or whatever fit the best for you 👍

2023-05-02 13:41 UTC, dmuharemagic commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
Sure, I'll PR to your fork to keep this one open. Thanks once again 👍

2023-06-13 06:58 UTC, FinKingma commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
hey @dmuharemagic is there any update on this change? Currently apicurio is still in a PoC phase at our client, but we could really use this fix so that we can use this gradle plugin as well. Otherwise we would have to create something similar ourselves

2023-06-13 06:59 UTC, FinKingma commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
it also looks like the initial issue I create at apicurio side has been closed now. Would it help for traceability to create a new one here?
https://github.com/Apicurio/apicurio-registry/issues/3301#event-9370824631

2023-06-15 18:13 UTC, dmuharemagic commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
@FinKingma I apologize for the delay. To expedite the process, I will divide the PR into two parts. One part will involve updating the internal Apicurio version, while the other part will focus on implementing support for user-defined extensions of `ArtifactType`. This approach will allow me to release the necessary fix quicker. You can expect the changes to be released by mid next week. Thank you for your support and for using the plugin. 🙂

2023-06-19 08:05 UTC, FinKingma commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
ah thanks @dmuharemagic for the update!

2023-06-25 19:19 UTC, dmuharemagic commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
@FinKingma It appears that the API changes resulting from the pull request at https://github.com/Apicurio/apicurio-registry/pull/2963 have a more significant impact than originally anticipated. The ArtifactType is now directly mapped to a simple String in the internal API, and unfortunately, the current version of the Java SDK does not provide a way to retrieve the list of registered artifact types (although it is possible through the REST API, I will need to integrate the call using a custom HTTP client). As a result, the task will require more time to complete. Upgrading the Apicurio version cannot be separated from these implicit API changes. I have two options: either submit a pull request to the Apicurio repository to include the necessary call in their Java SDK or refactor the underlying communication with the registry using a custom HTTP client instead of the Java SDK. I apologize for the delay. I am fully committed to resolving this issue and will provide the required upgrade soon.

2023-06-27 07:53 UTC, FinKingma commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
@dmuharemagic ah bummer, but thanks for the headsup, could you link the new issue once it is created?

2023-06-29 21:43 UTC, andreaTP commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
> submit a pull request to the Apicurio repository to include the necessary call in their Java SDK

Sorry for the late feedback! If you can open an issue in apicurio-registry for the endpoint that is needed I'll be happy to take it!

2023-06-30 08:22 UTC, andreaTP commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
@dmuharemagic Really sorry for the late feedback but this thread went into Spam 😥 
I added the missing API to the Registry Client library, please let me know if there is anything left I can do to facilitate.

2023-06-30 08:26 UTC, dmuharemagic commented on plugin/src/functionalTest/groovy/net/croz/apicurio/task/download/SchemaRegistryDownloadTaskSpecification.groovy
> +        assertArtifactExistsAndIsReadable(metadata.outputPath, "${metadata.name}.${artifactType}")
@andreaTP Sorry, missed your reply last night. Thank you for opening the issue and the quick implementation, really simplifies things on my end. 🙂
@FinKingma Sure, I'll link the new issue.

2025-09-10 20:00 UTC, andreaTP commented
Closing as outdated, I hope someone will pick it up.

2025-09-10 20:00 UTC, closed without merging